# gemini_advisor.py
import os
import logging
from typing import Set, Optional
import google.generativeai as genai
from dotenv import load_dotenv

logger = logging.getLogger("lumora-advisor")
load_dotenv()

DEFAULT_MODEL = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")
FALLBACK_MODELS = ["gemini-1.5-pro", "gemini-pro", "gemini-flash-latest"]

def generate_career_advice(user_skills: Set[str], goal: str, level: str, top_course=None) -> str:
    """Generate personalized career roadmap and advice for students."""
    
    api_key = os.getenv("GEMINI_API_KEY")
    
    # If no API key, return fallback advice
    if not api_key:
        return f"""# 🎯 Personalized Career Strategy & Learning Path

**Target Goal:** {goal}  
**Experience Level:** {level.title()}

### 1. Focus on Foundational Mastery
Start by strengthening your core competencies in **{goal}**. Complete foundational courses and practice hands-on exercises daily.

### 2. Build High-Impact Portfolio Projects
- Build 2-3 end-to-end projects demonstrating your skills.
- Document your codebase on GitHub and write clear README summaries.

### 3. Continuous Learning & Next Steps
- Follow structured milestones and practice interview problems regularly.
- Network with peers and participate in student tech communities.

### Current Status:
- You already know: {', '.join(user_skills) if user_skills else "Not specified"}
- Your level: {level}
- Recommended starting point: {getattr(top_course, 'name', None) or top_course or "Foundational Course"}

### Timeline:
- **3-6 months** to build core skills
- **6-12 months** to become job-ready
- **12-18 months** to advance to senior roles

---

## 2. Skill Analysis

### Skills You Already Have ✅
{', '.join(user_skills) if user_skills else "None listed"}

### Skills to Focus On 🎯
Based on your goal of becoming a {goal}, focus on:
1. **Core Fundamentals** - Build strong foundations
2. **Technical Skills** - Learn tools and technologies
3. **Practical Experience** - Build projects
4. **Soft Skills** - Communication, teamwork, problem-solving

### Recommended Learning Order:
1. Start with foundational concepts
2. Move to intermediate topics
3. Build projects to apply learning
4. Advance to specialized topics

---

## 3. Learning Strategy & Portfolio Projects

### Daily Study Plan (2 hours/day):
- **30 min** - Theory/Concepts
- **60 min** - Hands-on practice
- **30 min** - Project work

### Weekly Goals:
- Complete 1-2 modules
- Build 1 small project
- Practice coding daily

### Resources:
- Online courses (Coursera, edX, Udemy)
- YouTube tutorials
- Documentation and blogs
- Community forums (Stack Overflow, Reddit)

### Portfolio Project Ideas:
- Build 2-3 end-to-end projects demonstrating your skills
- Document your codebase on GitHub
- Write clear README summaries

---

## 4. Career & Internship Opportunities

### Job Roles:
- Entry-level positions
- Junior developer/analyst
- Internships
- Freelance opportunities

### Companies Hiring:
- Tech companies
- Startups
- Consulting firms
- Non-tech companies with tech departments

### In-Demand Domains:
- Web Development
- Data Science & ML
- Cloud Computing
- Cybersecurity

### Salary Ranges:
- Entry: $60,000 - $80,000/year
- Mid-level: $80,000 - $120,000/year
- Senior: $120,000 - $160,000/year

---

## 5. Action Plan & Next Steps

### Immediate Actions (Next 7 Days):
- [ ] Complete 1-2 beginner courses
- [ ] Set up your development environment
- [ ] Join 1 online community
- [ ] Build your first small project

### Milestones to Celebrate:
- 🎉 Complete first course
- 🎉 Build first project
- 🎉 Get first certificate
- 🎉 Apply to first job

### Encouragement:
Remember: Every expert was once a beginner. Consistent effort > Perfection.

**You've got this!** 💪

---

*This report was generated by PathPilot AI*
*Visit us at: https://pathpilot.streamlit.app*
"""

    # If API key exists, try Gemini with fallback models
    skills_str = ", ".join(user_skills) if user_skills else "Not specified"
    course_name = getattr(top_course, "name", None) or (top_course if isinstance(top_course, str) else "Foundational Course")
    
    prompt = f"""
You are an expert career counselor and learning path advisor helping students achieve their goals.

Student Profile:
- Goal: {goal}
- Current Skills: {skills_str}
- Experience Level: {level}
- Top Recommended Course: {course_name}

Please provide a comprehensive career and learning advice report including:

1. **Career Path Overview**
   - What the student needs to achieve their goal
   - Realistic timeline and expectations

2. **Skill Analysis**
   - Current strong skills
   - Key missing skills to prioritize next

3. **Learning Strategy & Portfolio Projects**
   - Practical study plan for their level
   - 2-3 real-world portfolio project ideas

4. **Career & Internship Opportunities**
   - Matching job roles and career paths
   - In-demand industry domains

5. **Action Plan & Next Steps**
   - Weekly learning plan
   - Encouraging advice to start immediately

Format the response with clear markdown headings, bold highlights, and motivating language. Do not mention model names or internal instructions.
"""
    
    # Try multiple models with fallback
    models_to_try = [DEFAULT_MODEL] + [m for m in FALLBACK_MODELS if m != DEFAULT_MODEL]
    last_error = None

    for m_name in models_to_try:
        try:
            genai.configure(api_key=api_key)
            model = genai.GenerativeModel(m_name)
            response = model.generate_content(prompt)
            if response and response.text:
                return response.text
        except Exception as e:
            last_error = e
            logger.warning(f"Model {m_name} failed: {e}")
            continue

    # If all Gemini models fail, return fallback advice
    logger.error(f"Failed to generate advice: {last_error}")
    return f"""# 🎯 Career Roadmap & Action Plan

**Target Goal:** {goal}  
**Experience Level:** {level.title()}

### 1. Core Learning Strategy
Begin with your top recommended course: **{course_name}**. Focus on practical problem solving and building foundational confidence.

### 2. Priority Skills to Master Next
Review your skill gap breakdown and prioritize the highest-impact missing skills.

### 3. Portfolio Building
Develop practical projects showcasing your skills and push them to your public portfolio.

### Current Status:
- You already know: {skills_str}
- Your level: {level}
- Recommended starting point: {course_name}

### Timeline:
- **3-6 months** to build core skills
- **6-12 months** to become job-ready

### Skills to Focus On 🎯
Based on your goal of becoming a {goal}, focus on:
1. **Core Fundamentals** - Build strong foundations
2. **Technical Skills** - Learn tools and technologies
3. **Practical Experience** - Build projects

### Immediate Actions:
- [ ] Start with your recommended course
- [ ] Set up your development environment
- [ ] Join online communities
- [ ] Build your first project

---

*This report was generated by PathPilot AI*
*Visit us at: https://pathpilot.streamlit.app*
"""