# simplified_gemini_advisor.py
from typing import Set, Optional

def generate_career_advice(user_skills: Set[str], goal: str, level: str, top_course=None):
    """Generate career advice (without Gemini fallback)"""
    
    skills_str = ", ".join(user_skills) if user_skills else "Not specified"
    course_name = top_course.name if top_course and hasattr(top_course, 'name') else "Not specified"
    
    return f"""
# 🚀 Personalized Career Report

## 1. Career Path Overview
Based on your goal of becoming a **{goal}**, here's your personalized roadmap.

### Current Status:
- You already know: {skills_str}
- Your level: {level}
- Recommended starting point: {course_name}

### Timeline:
- **3-6 months** to build core skills
- **6-12 months** to become job-ready
- **12-18 months** to advance to senior roles

---

## 2. Skill Analysis

### Skills You Already Have ✅
{', '.join(user_skills) if user_skills else "None listed"}

### Skills to Focus On 🎯
Based on your goal of becoming a {goal}, focus on:
1. **Core Fundamentals** - Build strong foundations
2. **Technical Skills** - Learn tools and technologies
3. **Practical Experience** - Build projects
4. **Soft Skills** - Communication, teamwork, problem-solving

### Recommended Learning Order:
1. Start with foundational concepts
2. Move to intermediate topics
3. Build projects to apply learning
4. Advance to specialized topics

---

## 3. Learning Strategy

### Daily Study Plan (2 hours/day):
- **30 min** - Theory/Concepts
- **60 min** - Hands-on practice
- **30 min** - Project work

### Weekly Goals:
- Complete 1-2 modules
- Build 1 small project
- Practice coding daily

### Resources:
- Online courses (Coursera, edX, Udemy)
- YouTube tutorials
- Documentation and blogs
- Community forums (Stack Overflow, Reddit)

---

## 4. Career Opportunities

### Job Roles:
- Entry-level positions
- Junior developer/analyst
- Internships
- Freelance opportunities

### Companies Hiring:
- Tech companies
- Startups
- Consulting firms
- Non-tech companies with tech departments

### Salary Ranges:
- Entry: $60,000 - $80,000/year
- Mid-level: $80,000 - $120,000/year
- Senior: $120,000 - $160,000/year

---

## 5. Motivation & Next Steps

### Immediate Actions (Next 7 Days):
- [ ] Complete 1-2 beginner courses
- [ ] Set up your development environment
- [ ] Join 1 online community
- [ ] Build your first small project

### Milestones to Celebrate:
- 🎉 Complete first course
- 🎉 Build first project
- 🎉 Get first certificate
- 🎉 Apply to first job

### Encouragement:
Remember: Every expert was once a beginner. Consistent effort > Perfection.

**You've got this!** 💪

---

*This report was generated by PathPilot AI*
*Visit us at: https://pathpilot.streamlit.app*
"""